### ISSUE TITLE
Able to find hotels, but unable to filter them

### ISSUE THREAD

**Issue by Ad0ntis123** [mrozekma/gencon-hotel-check#10]
Thank you for your work in keeping this up to date, it's let me get good rooms every year since you've started.

Since todays update it does work and polls the hotel rooms, however it does not filter down based on --connected or --max-distance.  

I've included a capture of the last time I ran it, as you can see I used --max-distance 3 and it even says 'within 3.0 blocks' but shows ones from 6.0, 4.0, and 6.0 in results.

Searching... (1 guest, 1 room, 2022-08-04 - 2022-08-07, within 3.0 blocks)
Results:   (2022-02-16 15:14:25.165000)
   Distance        Price      Hotel                                                                            Room
    6.0 blocks     $747       Homewood Suites Indianapolis Canal IUPUI                                         (1) 1 King Bed Studio Suite w/Pullout Sofa
    4.0 blocks     $921       Sheraton Indianapolis City Centre Hotel                                          (1) Executive King Suite w/Pullout Sofa
    6.0 blocks     $615       Tru by Hilton Indianapolis Downtown                                              (1) 1 King Bed

**Comment by mrozekma** [comment]
This is normal. The distance/price/name filters only control whether the script alerts you about a room (which will print an `!` to the left of it and trigger any [alerts](https://github.com/mrozekma/gencon-hotel-check#alerts) you've enabled), but all downtown rooms with availability are always printed

I might change that behavior, it confused someone else in #3.
