### ISSUE TITLE
I think the dates in the script are wrong.

### ISSUE THREAD

**Issue by dahc57** [mrozekma/gencon-hotel-check#14]
https://github.com/mrozekma/gencon-hotel-check/blob/34056a9fcc4a162bc00cabec37faf4e4b15921b3/gencon-hotel-check.py#L29

On the line above, it looks like the date is searching in 2022 instead of 2023.

**Comment by mrozekma** [comment]
Classic. I thought it was weird that it wasn't showing any hotels, even the ones miles out. Fixed now, thanks

**Comment by dahc57** [comment]
It happens to the best of us.

Thanks again for the script. It's fantastic.
