### ISSUE TITLE
Struggling clueless noob.

### ISSUE THREAD

**Issue by wjpennington** [mrozekma/gencon-hotel-check#15]
Last time I used this was 2017. I've tried and tried again, but no matter what, I get nowhere. Just path errors or it simply just repeats the option again without setting anything.  I can't get the script to run, nor set any parameters after following the guidance in the usage section. Python is up to date.  I sadly need a step-by-step idiot list (download, where the directory goes, how to start script)  on setup and parameter entry, as apparently I'm a moron and can't figure this out on my own despite having done so back in the day. I've exhausted my own efforts, so please don't think I'm n just asking idly, but if I haven't fixed this after eight hours, I'm never going to on my own.

There used to be guidance for setting up a bat file for this, that would just run the script once you set all of the parameters in the bat file. Does that still work?

**Comment by mrozekma** [comment]
If somebody wrote a batch script for this, I don't think it was me, I don't recall anything like that. Can you post the command you're running (leave out the passkey URL, you want to keep that secret) and the output you get?

It sounds like you're on Windows, so you should need to:

* Download the script, either using the git command in the [usage docs](https://github.com/mrozekma/gencon-hotel-check#usage), or by just downloading https://raw.githubusercontent.com/mrozekma/gencon-hotel-check/master/gencon-hotel-check.py in your browser
* Open a command prompt (Win+R, run `cmd`)
* Switch to the directory you download the script to (for example, `cd \users\name\downloads`)
* Run `py -3 gencon-hotel-check.py --url ...`

**Comment by wjpennington** [comment]
ok, cleared all of this up as windows was just refusing to recognize paths to actually run python. got everything going except email fgenerating a text message to my verizon number verizon, but will keep trial and erroring that till it works.

is this the correct format (dummy number and fake email used of course)

--email smtp.gmail.com myemail@gmail.com 1234567890@vtext.com

And just entering a blank for the password?

**Comment by mrozekma** [comment]
That's right, except the script is going to send the e-mail from your gmail account, so it needs your actual password. Or if you use two-factor authentication, it needs an app password, which you can generate by:

* Go to https://myaccount.google.com/security
* Click "2-Step Verification"
* Go to the bottom and click "App Passwords"
* For the app, select "Custom" and enter "gencon-hotel-check"
* Copy the 16 character password it generates and use that when the script asks for your e-mail password

**Comment by wjpennington** [comment]
thanks. I've gotten it top email. Unfortunately, Verizon has pretty much abandoned supporting for their vtext.com gateway for sending messages to their phones. Searched and found lots of Verizon users confirming it doesn't work, or has delays of 6 hours to days. Not complaining to you, just putting it out there for general awareness. 

"When it comes to the Vtext.com option, we are unable to provide any assurance regarding the timeliness or receipt of messages. This is due to the inherent limitations of internet email. Additionally, as a large amount of malicious messages to our customer originate through email, at times messages may be throttled or blocked as a whole. This behavior is not unique to Verizon Wireless and can happen with other providers to protect their customers from unwanted or malicious messages. "

**Comment by wjpennington** [comment]
Thanks for your help.  I'll just try to watch it manually when I'm home.  Text messages don't work to verizon any more. Emails to self don't work (tried multiple emails, no error messages, but nothing ever arrives, despite setitng up the app passwords), popups require windows32api, and I can't decipher how heck to do with that.  Gencon is not worth this much work.  Just closing this out.

**Comment by mrozekma** [comment]
Personally I use [Pushbullet](https://www.pushbullet.com/) to receive notifications, it's pretty straightforward and you can get them on a bunch of devices at once. You might also look at https://genconhotels.com/, it's the same kind of tool but web-based, so you might have an easier time.
