### ISSUE TITLE
Alerts don't seem to be triggering often

### ISSUE THREAD

**Issue by timothyfroehlich** [mrozekma/gencon-hotel-check#2]
I've had the --popup and browser alerts on, and while they work fine with --test, of the 4 or 5 rooms I've seen go by on the search the past few days, I've only had the alert work once. I even tried restarting the script while there was availability and it didn't work. Not sure what the issue is.

That said, by watching the command line output, my friends and I were able to upgrade from an airport hotel to a JW Marriott one :)

**Comment by mrozekma** [comment]
Never managed to reproduce this
