### ISSUE TITLE
Connected distance search

### ISSUE THREAD

**Issue by Joseph67843** [mrozekma/gencon-hotel-check#3]
Michael, thanks a ton for putting this together!  I'm running a search with max-distance connected, and it's finding a hotel 5 blocks away - is that intentional?

--- Text returned by the script ---

Searching... (1 guest, 1 room, 2019-07-31 - 2019-08-04, connected)
Results:   (2019-06-09 12:38:08.911231)
   Distance        Price      Hotel                                                                            Room
    5.0 blocks     $912       The Alexander                                                                    (1) Deluxe Queen Queen

--- The ICC list of connected and nearby hotels lists the Alexander as nearby but not connected ---

https://www.icclos.com/hotels.aspx

**Comment by mrozekma** [comment]
This is normal. The distance/price/name filters only control whether the script alerts you about a room (which will print an `!` to the left of it and trigger any [alerts](https://github.com/mrozekma/gencon-hotel-check#alerts) you've enabled), but all downtown rooms with availability are always printed
