### ISSUE TITLE
Getting 403 errors

### ISSUE THREAD

**Issue by quoid** [mrozekma/gencon-hotel-check#4]
I haven't used the script since last year but now (with the updated version from yesterday) I am getting 403 failed session requests.

`Session request failed: HTTP Error 403: Forbidden`

Here's my command:
`python gencon-hotel-check.py --key XXXXXXXX-XXXX Surname --show-all`

Tests work as intended

**Comment by daybreaker** [comment]
It looks like gencon switched up their authorization process again. I have a ruby version of the script that I'm trying to get running, and cant so far. Its a work in progress.

**Comment by daybreaker** [comment]
If you already booked a room, XXXXXXXX-XXXX should be XXXXXXXX. 

If you didnt already book a room, Surname should be the YYYYYYY....YYYYY in the second part of the initial reg page URL instead.

**Comment by quoid** [comment]
I might have gotten my codes codes crossed, will double check once I am back home.

PS - did you get your ruby version working?

**Comment by mrozekma** [comment]
> If you already booked a room, XXXXXXXX-XXXX should be XXXXXXXX.

To clarify, if you've already booked a room, your assigned housing portal key is no longer valid, so the script now takes your acknowledgement number and surname instead. The `XXXXXXXX` here is your acknowledgement number, which was displayed when you booked your room but should also be in the status column on the [housing page](https://www.gencon.com/housing). I just tested both ways and they worked, so I suspect you're passing in the wrong value there.

**Comment by daybreaker** [comment]
@quoid  I did, but only for people without a room. I had my argument input wrong. So it wasnt anything new with the cookies. Just me being dumb.

Still need to modify it so it works for people with reservations.

It was basically just me converting this one to ruby, because I know it better than Python 😛  But then I got lazy and didnt add all the cool stuff I wanted.

**Comment by quoid** [comment]
> so I suspect you're passing in the wrong value there.

I suspect the same, since I am being passed the information from another person, I think they might be giving me the portal key when I need the acknowledgment (without the 4 digit suffix)

**Comment by quoid** [comment]
Just verified, I was using the portal key rather than the acknowledgement key. Everything works as expected!

Sorry for the confusion!
