### ISSUE TITLE
Issue sending multiple emails

### ISSUE THREAD

**Issue by xominous** [mrozekma/gencon-hotel-check#5]
When attempting to send alerts to multiple emails, it appears to just email the last one listed in the chain the number of times the --email command was entered.

I used the following structure:

    --email smtp.gmail.com FROMEmailAddress TOEmailAddress1 --email smtp.gmail.com FROMEmailAddress TOEmailAddress2 --email smtp.gmail.com FROMEmailAddress TOEmailAddress3

**Comment by mrozekma** [comment]
Interesting. I would've expected that to work, but have never actually tried it. I'll look into fixing it.

**Comment by mrozekma** [comment]
Fixed now. Also you can simplify it with this:

    --email smtp.gmail.com FROMEmailAddress TOEmailAddress1,TOEmailAddress2,TOEmailAddress3
