### ISSUE TITLE
Throttling by the housing portal?

### ISSUE THREAD

**Issue by mark-friedman** [mrozekma/gencon-hotel-check#6]
After running the program for a while I tried to manually log into the housing portal and saw the following error message in my browser:
```
  GovernorMessageManagerHelper.checkThreshold::GM_202:Message Threshold exceeded
```
  Could that be related to the hotel checker program running?

**Comment by mark-friedman** [comment]
Ping @mrozekma

**Comment by mrozekma** [comment]
Possibly, but I'm running it too and haven't seen that yet. It might've just been a temporary problem in the housing portal

**Comment by mrozekma** [comment]
Looks like a common problem: https://www.reddit.com/r/gencon/comments/f28wvq/error_when_accessing_housing_portal/
