### ISSUE TITLE
I am a noob

### ISSUE THREAD

**Issue by mmg-glitch** [mrozekma/gencon-hotel-check#7]
I've been trying to get this to work all day and am embarrassed, but out of idea's at what I am doing wrong. I have used Python in the past, but  it's been a long time ago, and I am not a coder at all. I either am putting the key in the wrong place or not remove enough of the example code or something. It always gives me a syntax error, I also tried the whole url, as the alternative but same results. Can you show an example of what and where you put your key in at? 
Here is where I thought it went and how I put mine in: ( I tried a ton of different ways)

```
group = parser.add_argument_group('required arguments')
# Both of these set 'key'; only one of them is required
qroup.add_argument('--key 32XXXXX6-GE52/18XXX737ecaXXXXXX54adb8ff9a6e5a08XXXab0723abbd81XXXXXXbfdXXXbbc4', nargs = 2, metavar = ('KEY', 'AUTH'), help = 'key (see the README for more information)')
group.add_argument('--url', action = PasskeyUrlAction, dest = 'key', help = 'passkey URL containing your key')
```

Thanks in advance!

**Comment by Shmajumd** [comment]
Not sure exactly where you're going wrong, but in case it's helpful, this is the command I run from cmd and it's working fine (with some obvious replacements)

> python gencon-hotel-check.py --key K3YG0H34 Lastname --email smtp.gmail.com myemail@gmail.com myemail@gmail.com  --guests 5

The 8 character bit after --key is what I see in parentheses after "Room request Modified" in the Status column on gencon.com/housing
I didn't have to change anything in the code itself, I just provided --key, --email to email myself results, and --guests to filter for big enough rooms.  Pretty painless.

**Comment by mrozekma** [comment]
Are you editing your key into the code? You don't need to do that; the code you posted is defining command-line arguments you pass in. If you run `python gencon-hotel-check.py --help` it will print out some info about how to call it. If you don't have a room yet, you want to run it like this:

    python gencon-hotel-check.py --key 32XXXXX6-GE52 18XXX737ecaXXXXXX54adb8ff9a6e5a08XXXab0723abbd81XXXXXXbfdXXXbbc4

You'll probably want some other arguments to control things like which hotels are listed and how you get alerted when rooms are available; `--help` or the [README](https://github.com/mrozekma/gencon-hotel-check) should be able to help with that. But the command I posted should be enough for it to successfully search for rooms

**Comment by mmg-glitch** [comment]
Thank you both, I was putting my key into the code. It never occurred me that my key went into the command-line. Thank you again!
