### ISSUE TITLE
Recent "Failed to decode reservation: Expecting value: line 1 column 1 (char 0)" error?

### ISSUE THREAD

**Issue by geddingsworth** [mrozekma/gencon-hotel-check#8]
Been running the script regularly since the lottery, and everything seems to have been working great. But just today I started getting this error when I try to run it. Something change on the housing portal side maybe?

For reference, the command I've been running:

gencon-hotel-check.py --key [XXXXXXXX] [Lastname] --popup --wednesday --show-all

**Comment by Shmajumd** [comment]
I've had it running uninterrupted without error, but I also haven't stopped/started it in weeks.  What error do you get?

**Comment by geddingsworth** [comment]
Whoops, only put the error in the title. Here's the full output:

Searching... (1 guest, 1 room, 2020-07-29 - 2020-08-02, downtown)
Failed to decode reservation: Expecting value: line 1 column 1 (char 0)

It then repeats that every time it would checks the portal (I think it's every minute).

**Comment by Shmajumd** [comment]
hah, damn.  I stopped and re-ran mine to see what'd happen and now I get the same error.  I think you might be right and now I regret testing it D:

**Comment by mrozekma** [comment]
Looks like Passkey added a captcha when looking up an existing reservation.

![](https://user-images.githubusercontent.com/444512/76056947-e6560280-5f45-11ea-8241-49b6aa53a985.png)

They claim it's ["part of ongoing security improvements"](http://cvent.force.com/06PKYx1amp4ZuYor2G/articles/Release_Note/000072557). If I worked there I'd be more focused on making a decent API to help people trying to get info from the site, but that's not my call.

I'll look into a user-friendly way to fix it. It looks like you only need to solve the captcha once, so it should be doable. In the meantime if you have someone who hasn't booked a room yet, the new reservation workflow is unchanged, so the script should still work that way.

**Comment by mrozekma** [comment]
This is fixed now. See the [README](https://github.com/mrozekma/gencon-hotel-check) for new usage info; you need to get a URL from the housing website and pass it in with `--url`.

**Comment by Ad0ntis** [comment]
I have downloaded the new update, but I'm getting the following when attempting to use the script.  Is this something I'm doing wrong?

gencon-hotel-check.py: error: argument --url: invalid passkey url: ''https://book.passkey.com/event/#######/owner/100/r/XXXXXXXXX/YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY''

**Comment by mrozekma** [comment]
@Ad0ntis I think you used single quotes around the URL on Windows. That would work on Linux or OSX, but Windows' shell isn't very good; you need to use double quotes (`"`)

**Comment by Ad0ntis** [comment]
@mrozekma That seems to have done the trick, I appreciate it!
