### ISSUE TITLE
No longer works with 2022 system

### ISSUE THREAD

**Issue by Ad0ntis123** [mrozekma/gencon-hotel-check#9]
I attempted to get this to work for the housing portal that went up yesterday, but it seems they have changed something and it no longer works.  I get invalid URL, and the URL for me when I do not have a room no longer matches the example in the readme.

**Comment by mrozekma** [comment]
Yeah, it changed a bit. I looked at it tonight and think I know how to fix it, they actually made it a bit simpler. Should be fixed in the next day unless I run into something unexpected
